export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const SET_USER_UNFO = "SET_USER_UNFO";
export const SET_ERROR_REQUEST = "SET_ERROR_REQUEST";
export const SET_USER_REPOS = "SET_USER_REPOS";
export const SET_LOADIND = "SET_LOADIND";
