export const SET_USER_UNFO = "SET_USER_UNFO";
export const SET_ERROR_REQUEST = "SET_ERROR_REQUEST";
export const SET_USER_REPOS = "SET_USER_REPOS";
export const SET_LOADIND_USER_INFO = "SET_LOADIND_USER_INFO";
export const SET_LOADIND_USER_REPOS = "SET_LOADIND_USER_REPOS";
export const SET_ERROR_USER_NOT_FOUND = "SET_ERROR_USER_NOT_FOUND";
